### ISSUE TITLE
Missing symbols for esp8266

### ISSUE THREAD

**Issue by davidgraeff** [platformio/platformio-pkg-ldscripts#1]
Look at https://github.com/esp8266/Arduino/commit/70cf3c36ef2519d8609423faf7bf8d3c8b0b0345.
They added Td0, Td4s and rcons which is necessary for newer espressif sdks

**Comment by ivankravets** [comment]
That changes were implemented in https://github.com/platformio/platformio-pkg-ldscripts/tree/esp8266_stage branch. See https://github.com/platformio/platformio-pkg-ldscripts/blob/esp8266_stage/esp8266.flash.common.ld#L564

More details https://github.com/platformio/platformio/issues/401#issuecomment-166958952
