### ISSUE TITLE
Getting started to modify "memory maps"

### ISSUE THREAD

**Issue by meron1122** [platformio/platformio-pkg-ldscripts#2]
Hi!
I actualy experiment with esp8266 - example, i  solder flash W25Q128 (16mb), and i have question.
how to property edit this "memory maps", is any tips to edit files? ;)

**Comment by valeros** [comment]
Hi @meron1122! Which example do you want to try with `Arduino` or `SDK`?

**Comment by meron1122** [comment]
For example, i want to extend spiffs size.
I use arduino.

**Comment by valeros** [comment]
Default [`16MB`](https://github.com/platformio/platformio-pkg-ldscripts/blob/master/esp8266.flash.16m.ld) linker script has `15MB` spiffs partition, is it enough for you?
Just add to your environment in `platformio.ini` next line:

``` ini
build_flags = -Wl,-T"esp8266.flash.16m.ld"
```

**Comment by meron1122** [comment]
Thanks i think this solved my issue, but, by the way, Do you have any link, to read about this mapping scripts? ;)

**Comment by valeros** [comment]
I haven't seen an extensive manual, but there is some information about this topic in the Arduino issues, for example [here](https://github.com/esp8266/Arduino/issues/1163).

**Comment by pieman64** [comment]
Thanks @valeros I quickly looked at that earlier today but I have to confess it didn't mean much to me.

**Comment by ivankravets** [comment]
This is obsolete repo for PlatfomIO 2.0. We will remove it later. Use https://github.com/platformio/platform-espressif8266 instead
